### ISSUE TITLE
docker-compose usage example

### ISSUE THREAD

**Issue by frode** [simonszu/webtrees-docker#4]
Hi @simonszu any chance you could provide an example of how to use this docker image with docker-compose?

Regards
Frode

**Comment by simonszu** [comment]
Depends. I do not run my containers with docker-compose but with Ansible's [docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html) module, which has a similar syntax, but not exactly the same. While i think this will help people run the container, it isn't proper docker-compose syntax, so i'll just paste it here, maybe someone who actually uses docker-compose can translate it. Here you go:

```
- name: Start webtrees docker service
  docker_container:
    name: webtrees
    image: simonszu/webtrees
    volumes:
    - "/data/webtrees:/var/www/html/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.webtrees.rule: "Host(`webtrees.mydomain.tld`)"
      traefik.http.routers.webtrees.entrypoints: "https"
      traefik.http.routers.webtrees.service: "webtrees"
      traefik.http.routers.webtrees.tls.certresolver: "le"
      traefik.http.services.webtrees.loadbalancer.server.port: "443"
      traefik.http.services.webtrees.loadbalancer.server.scheme: "https"
    networks:
      - name: backend
```

**Comment by frode** [comment]
> Depends. I do not run my containers with docker-compose but with Ansible's [docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html) module, which has a similar syntax, but not exactly the same. While i think this will help people run the container, it isn't proper docker-compose syntax, so i'll just paste it here, maybe someone who actually uses docker-compose can translate it. Here you go:
> 
> ```
> - name: Start webtrees docker service
>   docker_container:
>     name: webtrees
>     image: simonszu/webtrees
>     volumes:
>     - "/data/webtrees:/var/www/html/data"
>     labels:
>       traefik.enable: "true"
>       traefik.http.routers.webtrees.rule: "Host(`webtrees.mydomain.tld`)"
>       traefik.http.routers.webtrees.entrypoints: "https"
>       traefik.http.routers.webtrees.service: "webtrees"
>       traefik.http.routers.webtrees.tls.certresolver: "le"
>       traefik.http.services.webtrees.loadbalancer.server.port: "443"
>       traefik.http.services.webtrees.loadbalancer.server.scheme: "https"
>     networks:
>       - name: backend
> ```

Thank you! I will translate this into docker-compose format this evening :-)
I simply needed these parameters and labels.

Regards
Frode

**Comment by simonszu** [comment]
You're welcome. Most of the labels are for usage with traefik anyways, but yeah. I am still a little surprised to get this much attention for this image i have created mostly for myself ;) Please apologize my delays in answering issues and such.

**Comment by frode** [comment]
> 
> 
> You're welcome. Most of the labels are for usage with traefik anyways, but yeah. I am still a little surprised to get this much attention for this image i have created mostly for myself ;) Please apologize my delays in answering issues and such.

Yeah I noticed all of the traefik related labels. Traefik is awesome, using it for all my web services.
Guess its sometimes those small contributions that fills a gap here and there that gets the attention and gains popularity. I hope you will continue to maintain the docker image :) 👍

**Comment by frode** [comment]
@simonszu I guess you spin up a separate image for mariadb or mysql?

**Comment by frode** [comment]
Here is my draft so far, its simply by comparing some of my current docker-compose.yml content and factoring out this as two services: 
- db server with mariadb
- webtrees web server

``` yml
version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: webtrees_mariadb
    restart: always
    networks:
      - internal
    volumes:
      - path to mariadb data:/config
    environment:
      - MYSQL_ROOT_PASSWORD=secret password
      - MYSQL_DATABASE=webtrees
      - MYSQL_USER=webtrees
      - MYSQL_PASSWORD=secret password
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    labels:
      - traefik.enable=false
  webtrees:
    image: simonszu/webtrees
    container_name: webtrees_web
    restart: always
    depends_on:
      - mariadb
    networks:
      - internal
      - external
    ports:
      - 443:443
    volumes:
      - path to webtrees data:/var/www/html/data"
    labels:
      - traefik.enable=true
      - traefik.backend=webtrees
      - traefik.frontend.rule=Host:webtrees.domain.tdl
      - traefik.docker.network=external
      - traefik.port=443
      - traefik.protocol=https
networks:
  external:
    external:
      name: external
  internal:
    driver: bridge
```
